import { expect, test } from '@playwright/test';
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aV1sAAAAASUVORK5CYII=', 'base64');
test('real local storage: batch failures, manual correction, retry history, and results', async ({ page, request }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Create Test Tournament', exact: true }).click();
  await page.getByLabel('Tournament Name').fill(`E2E benchmark ${Date.now()}`);
  await page.getByRole('button', { name: 'Create Tournament', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('E2E benchmark');
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  await page.getByLabel('Upload screenshots', { exact: true }).setInputFiles([{ name: 'first.png', mimeType: 'image/png', buffer: png }, { name: 'second.png', mimeType: 'image/png', buffer: png }]);
  await page.getByRole('button', { name: 'Analyze 2 Screenshots' }).click();
  await expect(page.getByRole('status')).toContainText('2 / 2 completed', { timeout: 30_000 });
  await page.getByRole('button').filter({ has: page.locator('strong', { hasText: 'first.png' }) }).click();
  await expect(page.getByText('Workers AI is unavailable in offline mode.', { exact: false }).first()).toBeVisible();
  await page.getByRole('combobox', { name: 'Screen Type', exact: true }).selectOption('MATCH_SUMMARY');
  await page.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('BATTLE_ROYALE');
  await page.getByLabel('Map raw', { exact: true }).fill('BERMUDES');
  await expect(page.getByLabel('Map (canonical)', { exact: true })).toHaveValue('BERMUDA');
  await page.getByLabel('Placement', { exact: true }).fill('4');
  await page.getByLabel('Total Teams', { exact: true }).fill('12');
  await page.getByRole('button', { name: 'Add Player' }).click();
  const values = { 'Player name': '★ALL★STARS★_!!', Kills: '7', Assists: '4', Damage: '3868', Revives: '5', 'Survival time': '13:29' };
  for (const [label, value] of Object.entries(values)) await page.getByLabel(`Player 1 ${label}`, { exact: true }).fill(value);
  await page.getByRole('button', { name: 'Save Corrections', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Ground truth saved');
  await page.screenshot({ path: 'test-results/review-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Retry AI Analysis' }).click();
  await expect(page.getByRole('button', { name: 'Retry AI Analysis' })).toBeEnabled();
  await expect(page.getByRole('combobox', { name: 'Analysis attempt', exact: true }).locator('option')).toHaveCount(2);
  await expect(page.getByLabel('Player 1 Player name')).toHaveValue('★ALL★STARS★_!!');
  await page.getByRole('button', { name: 'Screenshots', exact: true }).click();
  await page.getByRole('button', { name: 'Test Results', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Test Results' })).toBeVisible();
  await expect(page.locator('.perfect-banner')).toContainText('0.0%');
  await expect(page.getByRole('cell', { name: 'Player name STRICT' })).toBeVisible();
  await page.screenshot({ path: 'test-results/results-desktop.png', fullPage: true });
  const exported = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export benchmark JSON' }).click(); expect((await exported).suggestedFilename()).toMatch(/^benchmark-/);
  // Unsupported content rejected by the actual Worker, not browser validation.
  const tournaments = await (await request.get('/api/tournaments')).json();
  const response = await request.post(`/api/tournaments/${tournaments[0].id}/screenshots`, { multipart: { file: { name: '../../fake.png', mimeType: 'image/png', buffer: Buffer.from('<script>bad</script>') } } });
  expect(response.status()).toBe(400);
  const workspace = await (await request.get(`/api/tournaments/${tournaments[0].id}`)).json();
  const shot = workspace.screenshots.find((s: { filename: string }) => s.filename === 'first.png');
  expect(shot.attempts).toHaveLength(2); expect(shot.attempts[0].status).toBe('FAILED'); expect(shot.correctedResult.players[0].name).toBe('★ALL★STARS★_!!');
});
test('mobile layout remains contained', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Free Fire Analytics', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
});
test('detailed stats are editable and persist numeric K/D/A and row ordering', async ({ page, request }) => {
  const name = `Detailed E2E ${Date.now()}`;
  const tournament = await (await request.post('/api/tournaments', { data: { name } })).json();
  const shot = await (await request.post(`/api/tournaments/${tournament.id}/screenshots`, { multipart: { file: { name: 'detailed.png', mimeType: 'image/png', buffer: png } } })).json();
  await page.goto('/');
  await page.getByRole('button').filter({ has: page.locator('strong', { hasText: name }) }).click();
  await page.getByRole('button').filter({ has: page.locator('strong', { hasText: 'detailed.png' }) }).click();
  await page.getByRole('combobox', { name: 'Screen Type', exact: true }).selectOption('DETAILED_STATS');
  await page.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('BATTLE_ROYALE');
  await page.getByLabel('Map raw', { exact: true }).fill('BERMUDES');
  await page.getByLabel('Placement', { exact: true }).fill('6');
  await page.getByLabel('Total Teams', { exact: true }).fill('12');
  await page.getByRole('button', { name: 'Add Player' }).click();
  const values = { 'Player name': '7C_TROJ4N!!', Kills: '2', Deaths: '2', Assists: '1', Damage: '1371', 'Actual damage': '1170', Knockdowns: '4', Healing: '983', Help: '0', Revives: '0', 'Headshot %': '0' };
  for (const [label, value] of Object.entries(values)) await page.getByLabel(`Player 1 ${label}`, { exact: true }).fill(value);
  await page.getByRole('button', { name: 'Add Player' }).click();
  await page.getByLabel('Player 2 Player name', { exact: true }).fill('#B');
  await page.getByRole('button', { name: 'Move player 2 up', exact: true }).click();
  await expect(page.getByLabel('Player 1 Player name', { exact: true })).toHaveValue('#B');
  await page.getByRole('button', { name: 'Delete player 1', exact: true }).click();
  await page.getByRole('button', { name: 'Save Corrections', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Ground truth saved');
  const saved = await (await request.get(`/api/screenshots/${shot.id}`)).json();
  expect(saved.correctedResult.players[0]).toMatchObject({ name: '7C_TROJ4N!!', kills: 2, deaths: 2, assists: 1, actualDamage: 1170, headshotRate: 0 });
  expect(saved.attempts).toHaveLength(0);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/detailed-mobile.png', fullPage: true });
});
